### ISSUE TITLE
TLS client: In state certify at ssl_handshake.erl:1952 generated CLIENT ALERT : Handshake Failure

### ISSUE THREAD

**Issue by msudgh** [getsentry/sentry-elixir#443]
### Environment

* Elixir version (elixir -v): Elixir 1.11.2
* Erlang/OTP version (erl): Eshell V11.1.3, Erlang/OTP 23
* Sentry version (mix deps): -> 8.0
* Operating system: macOS
* Is this an umbrella application?: Yeah
* Release type (Distillery, mix release, Mix, etc.): mix release

### Description

It seems in hackney as Sentry HTTP client configured with an old deprecated TLS version, I couldn't get more verbose but this's what logged at `after_send(event, error)/0` function.

```bash
02:29:02.888 [info]  TLS :client: In state :certify at ssl_handshake.erl:1952 generated CLIENT ALERT: Fatal - Handshake Failure
 - {:bad_cert, :hostname_check_failed}
```

Also inside Sentry's dashboard, no events received, config example:

```ex

config :sentry,
  dsn: System.get_env("SENTRY_DSN"),
  environment_name: Mix.env,
  enable_source_code_context: true,
  root_source_code_path: File.cwd!(),
  context_lines: 20,
  included_environments: [:prod, :dev],
  capture_log_messages: true,
  tags: %{
    env: System.get_env("MIX_ENV"),
    version: Mix.Project.config[:version]
  },
  before_send_event: {App.Utils.Sentry, :before_send}, after_send_event: {App.Utils.Sentry, :after_send},
  filter: App.Utils.Sentry.EventFilter

```

### Expected Behavior

- Updating hackney TLS version
- Sending Sentry events

### Actual Behavior

- Not receiving Sentry events

**Comment by mitchellhenke** [comment]
Thanks for opening an issue! What version of hackney are you on?

https://github.com/benoitc/hackney/issues/624 seems to be the problem, and it should be fixed in the most recent version of hackney (1.16.0).

**Comment by msudgh** [comment]
@mitchellhenke v1.16.0

**Comment by msudgh** [comment]
@mitchellhenke v1.6, I tried to clean `deps` & `_build` dirs and reinstalled packages but still reproducable.
I'm not sure shared dependencies managed in Hex but would be to be related to this line?
https://github.com/getsentry/sentry-elixir/blob/dac9c3eeccbaecba28dd8f1917c9ab13515f15b0/mix.exs#L39

**Comment by mitchellhenke** [comment]
hm, are you including `override: true` to use hackney v1.6? That version is quite old and not compatible with the latest major version of Sentry.

Could you try updating to hackney v1.16.0 and see if the issue persists?

**Comment by Fitblip** [comment]
Hey so I'm wondering if this is actually a regression for https://bugs.erlang.org/browse/ERL-1232 (or some other issue with the most recent erlang release), I'm running Erlang `23.1.4` from homebrew along with Elixir `1.11.2`, and hackney `1.16.0` and I'm seeing handshake failures for `gstatic.com`.

Example:
```
❯ iex -S mix
Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Interactive Elixir (1.11.2) - press Ctrl+C to exit (type h() ENTER for help)

iex(1)> :hackney.get('https://www.gstatic.com/')

20:38:37.530 [info]  TLS :client: In state :wait_cert_cr at ssl_handshake.erl:1952 generated CLIENT ALERT: Fatal - Handshake Failure
 - {:bad_cert, :hostname_check_failed}
{:error,
 {:tls_alert,
  {:handshake_failure,
   'TLS client: In state wait_cert_cr at ssl_handshake.erl:1952 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}'}}}
```

**Comment by msudgh** [comment]
@mitchellhenke Sry for the typo, I meant `v1.16.0`, not `v1.6`
@Fitblip Same to me on gstatic

```
Interactive Elixir (1.11.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :hackney.get('https://google.com')
{:ok, 301,
 [
   {"Location", "https://www.google.com/"},
   {"Content-Type", "text/html; charset=UTF-8"},
   {"Date", "Mon, 30 Nov 2020 11:42:32 GMT"},
   {"Expires", "Wed, 30 Dec 2020 11:42:32 GMT"},
   {"Cache-Control", "public, max-age=2592000"},
   {"Server", "gws"},
   {"Content-Length", "220"},
   {"X-XSS-Protection", "0"},
   {"X-Frame-Options", "SAMEORIGIN"},
 ], #Reference<0.848153534.725090306.201470>}
iex(2)> :hackney.get('https://www.gstatic.com/')
{:error,
 {:tls_alert,
  {:handshake_failure,
   'TLS client: In state wait_cert_cr at ssl_handshake.erl:1952 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}'}}}
iex(3)>
```

**Comment by mitchellhenke** [comment]
@msudgh @Fitblip thank you for the context and looking into it

I am going to close this issue for now as it seems to be an issue with hackney itself.
